#ifndef BSO_ANTIROOTKIT_LKM_CHECK_WP_BIT_H
#define BSO_ANTIROOTKIT_LKM_CHECK_WP_BIT_H

#define WP_BIT 0x10000
#define IS_WP_BIT_SET (read_cr0() & WP_BIT) == WP_BIT

#endif//BSO_ANTIROOTKIT_LKM_CHECK_WP_BIT_H
